# Generated by Django 5.2.16 on 2026-08-10 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyingfox_app', '0022_remove_blog_is_published_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=250)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('email_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Enquiry',
                'verbose_name_plural': 'Contact Enquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
