# Generated by Django 5.2.16 on 2026-08-10 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flyingfox_app', '0023_contactenquiry'),
        ('flyingfox_app', '0024_alter_offer_status'),
    ]

    operations = [
    ]
