# Generated by Django 5.2.15 on 2026-08-12 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyingfox_app', '0025_merge_0023_contactenquiry_0024_alter_offer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ml', 'Malayalam'), ('hi', 'Hindi'), ('ta', 'Tamil')], default='en', max_length=10),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='onboarding_step',
            field=models.CharField(choices=[('language', 'Waiting For Language'), ('name', 'Waiting For Name'), ('phone', 'Waiting For Phone'), ('email', 'Waiting For Email'), ('completed', 'Completed')], default='language', max_length=20),
        ),
    ]
