# Generated by Django 5.2.15 on 2026-08-12 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyingfox_app', '0026_chatsession_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='language',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='translated_message',
            field=models.TextField(blank=True),
        ),
    ]
