# Generated by Django 5.2.15 on 2026-08-13 05:09

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyingfox_app', '0027_chatmessage_language_chatmessage_translated_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rideprice',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('99999999.99'))]),
        ),
    ]
