# Generated by Django 5.2.15 on 2026-08-13 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyingfox_app', '0029_remove_userprofile_password_userprofile_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={},
        ),
        migrations.RemoveField(
            model_name='offer',
            name='coupon',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='discount_type',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='status',
        ),
        migrations.AddField(
            model_name='offer',
            name='auto_apply',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offer',
            name='buy_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='offer',
            name='coupon_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offer',
            name='first_booking_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offer',
            name='free_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='max_uses',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='max_uses_per_user',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='offer',
            name='maximum_discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='minimum_booking_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='offer',
            name='minimum_participants',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='offer',
            name='offer_type',
            field=models.CharField(choices=[('percentage', 'Percentage Discount'), ('fixed', 'Fixed Amount Discount'), ('buy_x_get_y', 'Buy X Get Y'), ('group', 'Group Discount'), ('first_booking', 'First Booking'), ('weekday', 'Weekday Offer'), ('early_bird', 'Early Bird'), ('birthday', 'Birthday Offer'), ('coupon', 'Coupon Offer')], default=23, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offer',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='offer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
