# Generated by Django 5.2.15 on 2026-08-14 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyingfox_app', '0030_alter_offer_options_remove_offer_coupon_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={'ordering': ['-created_at'], 'verbose_name': 'Offer', 'verbose_name_plural': 'Offers'},
        ),
        migrations.RemoveField(
            model_name='offer',
            name='rides',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='offer',
            name='ride',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='flyingfox_app.ride'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='offer_type',
            field=models.CharField(choices=[('percentage', 'Percentage Discount'), ('fixed', 'Fixed Amount Discount'), ('buy_x_get_y', 'Buy X Get Y'), ('group', 'Group Discount'), ('first_booking', 'First Booking'), ('weekday', 'Weekday Offer'), ('early_bird', 'Early Bird'), ('birthday', 'Birthday Offer'), ('coupon', 'Coupon Offer')], default='percentage', max_length=30),
        ),
        migrations.AlterField(
            model_name='offer',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=True),
        ),
    ]
