# Generated by Django 5.2.15 on 2026-08-14 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flyingfox_app', '0032_remove_booking_coupon_booking_adult_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='adult_count',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='child_count',
        ),
    ]
